name: GUI test
description: GUI Test
main: com.emmz.grich.grep.grep
version: 1.0
author: Grich
depend: [Spout]
commands:
   grep:
      description: GREP
      usage: /<command> - Opens user manager.
   whereami:
      description: GREP Location
      usage: /<command> - Shows your location.