name: Grep
description: Grichecth Reports
main: com.emmz.grich.grep.Grep
version: 0.6
author: Grichecth
depend: [Spout]
commands:
   grep:
      description: GREP
      usage: /<command> - Opens Gui.
   whereami:
      description: GREP Location
      usage: /<command> - Shows your location.