name: Grep
description: Grichecth Reporting
main: com.emmz.grich.grep.Grep
version: 0.6
author: Grichecth
depend: [Spout]
commands:
   grep:
      description: GREP
      usage: /<command> - Opens Gui.
